apiVersion: v1
kind: Service
metadata:
  name: meal-service
  labels:
    app: meal-service
spec:
  type: NodePort
  selector:
    app: meal-service
  ports:
  - port: 8085
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: meal-service-deployment
    labels:
        app: meal-service
spec:
    selector:
        matchLabels:
            app: meal-service
    template:
        metadata:
            labels:
                app: meal-service
        spec:
            containers:
            - name: meal-service
              image: berwoutv/meal-service:latest
              imagePullPolicy: Always
              env:
              - name: MONGO_URI
                value: ${MONGO_URI}
              ports:
              - containerPort: 80
              readinessProbe:
                httpGet:
                    path: /api/meals/health
                    port: 80
                initialDelaySeconds: 5
                periodSeconds: 5
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: dinner-planner-tls
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
  - match: (Host(`berwout.nl`) || Host(`www.berwout.nl`)) && Path(`/api/meals`)
    kind: Rule
    services:
    - name: meal-service
      port: 8085
  tls:
    certResolver: myresolver