apiVersion: v1
kind: Service
metadata:
  name: meal-service
  labels:
    app: meal-service
spec:
  type: NodePort
  selector:
    app: meal-service
  ports:
  - port: 8085
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: meal-service-deployment
    labels:
        app: meal-service
spec:
    selector:
        matchLabels:
            app: meal-service
    template:
        metadata:
            labels:
                app: meal-service
        spec:
            containers:
            - name: meal-service
              image: berwoutv/meal-service
              ports:
              - containerPort: 80
              readinessProbe:
                httpGet:
                    path: /api/meals
                    port: 80
                initialDelaySeconds: 5
                periodSeconds: 5
