apiVersion: v1
kind: Service
metadata:
  name: dinner-planner
  labels:
    app: dinner-planner
spec:
  type: NodePort
  selector:
    app: dinner-planner
  ports:
  - port: 8081
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: dinner-planner-deployment
    labels:
        app: dinner-planner
spec:
    selector:
        matchLabels:
            app: dinner-planner
    template:
        metadata:
            labels:
                app: dinner-planner
        spec:
            containers:
            - name: dinner-planner
              image: berwoutv/dinner-planner:latest
              imagePullPolicy: Always
              ports:
              - containerPort: 80
              readinessProbe:
                httpGet:
                    path: /
                    port: 80
                initialDelaySeconds: 5
                periodSeconds: 5
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: dinner-planner-tls
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`berwout.nl`) || Host(`www.berwout.nl`)
    kind: Rule
    middlewares:
    - name: redirect-scheme
      namespace: default
    services:
    - name: dinner-planner
      port: 8081
  tls:
    certResolver: myresolver