apiVersion: v1
kind: Service
metadata:
  name: blog-service
  labels:
    app: blog
spec:
  type: NodePort
  selector:
    app: blog
  ports:
  - port: 8080
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: blog-deployment
    labels:
        app: blog
spec:
    selector:
        matchLabels:
            app: blog
    template:
        metadata:
            labels:
                app: blog
        spec:
            containers:
            - name: blog
              image: berwoutv/blog
              ports:
              - containerPort: 80
              readinessProbe:
                httpGet:
                    path: /
                    port: 80
                initialDelaySeconds: 5
                periodSeconds: 5
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: blog-tls
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`blog.berwout.nl`)
    kind: Rule
    services:
    - name: blog-service
      port: 8080
  tls:
    certResolver: myresolver

