apiVersion: v1
kind: Service
metadata:
  name: ingredient-service
  labels:
    app: ingredient-service
spec:
  type: NodePort
  selector:
    app: ingredient-service
  ports:
  - port: 8082
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: ingredient-service-deployment
    labels:
        app: ingredient-service
spec:
    selector:
        matchLabels:
            app: ingredient-service
    template:
        metadata:
            labels:
                app: ingredient-service
        spec:
            containers:
            - name: ingredient-service
              image: berwoutv/ingredient-service
              ports:
              - containerPort: 80
              readinessProbe:
                httpGet:
                    path: /api/ingredients/health
                    port: 80
                initialDelaySeconds: 5
                periodSeconds: 5
