apiVersion: batch/v1
kind: Job
metadata:
  name: mongo-setup
  labels:
    app: mongo-setup
spec:
  template:
    spec:
      containers:
      - name: mongo-setup
        image: berwoutv/mongo-setup:latest
        imagePullPolicy: Always
      restartPolicy: Never